language: python

sudo: false

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=docs
  - TOXENV=pep8
  - TOXENV=py2pep8
  - TOXENV=packaging

install: pip install tox

script: tox
